version: "3"

services:
  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile
    volumes:
      - ./frontend:/code:cached
      - frontend_node_modules:/code/node_modules
    env_file:
      - .env
    hostname: vite
    ports:
      - "${DOCKER_FRONTEND_PORT}:8080"
    tty: true
    command: sleep infinity
  api:
    build:
      context: api
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/code:cached
      - api_node_modules:/code/node_modules
    env_file:
      - .env
    hostname: apollo
    ports:
      - "${DOCKER_API_PORT}:4000"
    tty: true
    command: sleep infinity
    depends_on:
      - db
  db:
    image: postgres:15.2-bullseye
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  frontend_node_modules:
  api_node_modules:
  postgres:
